### ISSUE TITLE
Detail prerequestite MySQL settings

### ISSUE THREAD

**Issue by aaronfitz** [SonarSoftware/freeradius_genie#1]
I ran though this guide on a fresh Ubuntu 16.04.1 LTS release and noticed the following -
1. MySQL is not configured to listen on a non-localhost address by default
2. MySQL is configured to perform reverse DNS lookups by default, so the login from Sonar may fail.

Settings that should be mentioned somewhere: mysql needs 'skip-name-resolve' in its configuration and the bind-address changed to 0.0.0.0.

**Comment by SonarSoftware** [comment]
Hi Aaron,

There is actually an option in the Genie already to set MySQL to listen on a public interface (specifically, the 'enableRemoteAccess' function in https://github.com/SonarSoftware/freeradius_genie/blob/master/src/DatabaseSetup.php.) This is accessible through the Genie CLI.

**Comment by aaronfitz** [comment]
I tried that option first -- didn't work. Unsure why; went to give the
script a cursory look to find out why but saw frameworks so just went for
the config files themselves ;)

**Comment by SonarSoftware** [comment]
If you want to dig into it, I'd like to get it fixed. It should work for either Maria or MySQL style config files.

The specific checks are:

If: /etc/mysql/mariadb.conf.d/50-server.cnf exists
/bin/sed -i 's/^bind-address/#bind-address/g' /etc/mysql/mariadb.conf.d/50-server.cnf

If: /etc/mysql/my.cnf
/bin/sed -i 's/^bind-address/#bind-address/g' /etc/mysql/my.cnf

Perhaps neither of those files exist in your system, or some similar simple error.

**Comment by aaronfitz** [comment]
Ahh, this makes sense. Fresh install of Ubuntu 16.04.1 LTS using mysql. /etc/mysql/my.cnf exists but the contents aren't the full config file like the system I have running 14.04.1.

I had to end up modifying
/etc/mysql/mysql.conf.d/mysqld.conf

Which isn't one of those two paths and explains why the script thought it worked

**Comment by SonarSoftware** [comment]
Yeah, that'd be why. The install instructions are for MariaDB rather than MySQL. I merged in your PR for anyone else using MySQL.
